# Import libraries

In [1]:
import pandas as pd

---
# 1. Data Ingestion

In [2]:
# Declare csv data types
dtypes_dict = {
    'customer_id': 'string',
    'customer_unique_id': 'string',
    'customer_zip_code_prefix': 'Int64',
    'customer_city': 'string',
    'customer_state': 'string'
}

customers_df = pd.read_csv("../Data/csvs/olist_customers_dataset.csv", dtype=dtypes_dict)
customers_df.name = "customers"
# customers_df.dtypes

In [3]:
# Declare csv data types
dtypes_dict = {
    'geolocation_zip_code_prefix': 'Int64',
    'geolocation_lat': 'Float64',
    'geolocation_lng': 'Float64',
    'geolocation_city': 'string',
    'geolocation_state': 'string'
}

geolocation_df = pd.read_csv("../Data/csvs/olist_geolocation_dataset.csv", dtype=dtypes_dict)
geolocation_df.name = "geolocation"
# geolocation_df.dtypes

In [4]:
# Declare csv data types
dtypes_dict = {
    'order_id': 'string',
    'order_item_id': 'Int64',
    'product_id': 'string',
    'seller_id': 'string',
    'shipping_limit_date': 'string',
    'price': 'Float64',
    'freight_value': 'Float64'
}

# It is not expected to have wrong dates format, so the conversion can be at reading
dates_columns = [
        "shipping_limit_date"
    ]

order_items_df = pd.read_csv(
    "../Data/csvs/olist_order_items_dataset.csv", 
    dtype=dtypes_dict,
    parse_dates=dates_columns
)
order_items_df.name = "order_items"
# order_items_df.dtypes

In [5]:
# Declare csv data types
dtypes_dict = {
    'order_id': 'string',
    'payment_sequential': 'Int64',
    'payment_type': 'string',
    'payment_installments': 'Int64',
    'payment_value': 'Float64'
}

order_payments_df = pd.read_csv("../Data/csvs/olist_order_payments_dataset.csv", dtype=dtypes_dict)
order_payments_df.name = "order_payments"
# order_payments_df.dtypes

In [6]:
# Declare csv data types
dtypes_dict = {
    'review_id': 'string',
    'order_id': 'string',
    'review_score': 'Int64',
    'review_comment_title': 'string',
    'review_comment_message': 'string',
    'review_creation_date': 'string',
    'review_answer_timestamp': 'string'
}

# It is not expected to have wrong dates format, so the conversion can be at reading
dates_columns = [
        "review_creation_date", 
        "review_answer_timestamp"
    ]

order_reviews_df = pd.read_csv(
    "../Data/csvs/olist_order_reviews_dataset.csv", 
    dtype=dtypes_dict,
    parse_dates=dates_columns
)
order_reviews_df.name = "order_reviews"
# order_reviews_df.dtypes

In [7]:
# Declare csv data types
dtypes_dict = {
    'order_id': 'string',
    'customer_id': 'string',
    'order_status': 'string',
    'order_purchase_timestamp': 'string',
    'order_approved_at': 'string',
    'order_delivered_carrier_date': 'string',
    'order_delivered_customer_date': 'string',
    'order_estimated_delivery_date': 'string'
}

# It is not expected to have wrong dates format, so the conversion can be at reading
dates_columns = [
        "order_approved_at", 
        "order_delivered_carrier_date", 
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]

orders_df = pd.read_csv(
    "../Data/csvs/olist_orders_dataset.csv", 
    dtype=dtypes_dict,
    parse_dates=dates_columns
)
orders_df.name = "orders"
# orders_df.dtypes

In [8]:
# Declare csv data types
dtypes_dict = {
    'product_id': 'string',
    'product_category_name': 'string',
    'product_name_lenght': 'Int64',
    'product_description_lenght': 'Int64',
    'product_photos_qty': 'Int64',
    'product_weight_g': 'Int64',
    'product_length_cm': 'Int64',
    'product_height_cm': 'Int64',
    'product_width_cm': 'Int64',
}

products_df = pd.read_csv("../Data/csvs/olist_products_dataset.csv", dtype=dtypes_dict)
products_df.name = "products"
# products_df.dtypes

In [9]:
# Declare csv data types
dtypes_dict = {
    'seller_id': 'string',
    'seller_zip_code_prefix': 'Int64',
    'seller_city': 'string',
    'seller_state': 'string',
}

sellers_df = pd.read_csv("../Data/csvs/olist_sellers_dataset.csv", dtype=dtypes_dict)
sellers_df.name = "sellers"
# sellers_df.dtypes

In [10]:
# Declare csv data types
dtypes_dict = {
    'product_category_name': 'string',
    'product_category_name_english': 'string'
}

product_category_name_translation_df = pd.read_csv("../Data/csvs/product_category_name_translation.csv", dtype=dtypes_dict)
product_category_name_translation_df.name = "product_category_name_translation"
# product_category_name_translation_df.dtypes

In [11]:
# Create dataframes dictionary
dfs_dict = {
    customers_df.name: customers_df,
    geolocation_df.name: geolocation_df,
    order_items_df.name: order_items_df,
    order_payments_df.name: order_payments_df,
    order_reviews_df.name: order_reviews_df,
    orders_df.name: orders_df,
    products_df.name: products_df,
    sellers_df.name: sellers_df,
    product_category_name_translation_df.name: product_category_name_translation_df
}

---
# 2. Data Quality Analysis

## Missing data

In [12]:
# Get what columns from which dataframes contains nulls
def check_nans(dfs_dict) -> None:
    for df in dfs_dict.values():
        nans_df = df.isna().sum()
        nans_df = nans_df[nans_df > 0]

        for column, quantity in nans_df.items():
            print(f"Nans in: {df.name} | Column: {column}. | Quantity: {quantity}")

In [13]:
check_nans(dfs_dict)

Nans in: order_reviews | Column: review_comment_title. | Quantity: 87656
Nans in: order_reviews | Column: review_comment_message. | Quantity: 58247
Nans in: products | Column: product_category_name. | Quantity: 610
Nans in: products | Column: product_name_lenght. | Quantity: 610
Nans in: products | Column: product_description_lenght. | Quantity: 610
Nans in: products | Column: product_photos_qty. | Quantity: 610
Nans in: products | Column: product_weight_g. | Quantity: 2
Nans in: products | Column: product_length_cm. | Quantity: 2
Nans in: products | Column: product_height_cm. | Quantity: 2
Nans in: products | Column: product_width_cm. | Quantity: 2

## Duplicates

In [14]:
unique_fields_dict = {
    customers_df.name: ["customer_id"],
    geolocation_df.name: ["geolocation_zip_code_prefix"],
    order_reviews_df.name: ["review_id"],
    orders_df.name: ["order_id"],
    products_df.name: ["product_id"],
    sellers_df.name: ["seller_id"]
}

def find_duplicates(dfs_dict, unique_fields_dict) -> None:
    duplicated_dict = {}
    for name, columns in unique_fields_dict.items():
        for column in columns:
            temp_s = dfs_dict[name][column].duplicated(keep=False)
            temp_ar = temp_s[temp_s].index.array
            if (temp_ar.size > 0):
                duplicated_dict[name] = {column: temp_ar}

    return duplicated_dict

In [15]:
duplicated_dict = find_duplicates(dfs_dict, unique_fields_dict)
duplicated_dict

{'geolocation': {'geolocation_zip_code_prefix': <PandasArray>
  [      0,       1,       2,       3,       4,       5,       6,       7,
         8,       9,
   ...
   1000153, 1000154, 1000155, 1000156, 1000157, 1000158, 1000159, 1000160,
   1000161, 1000162]
  Length: 999120, dtype: int64},
 'order_reviews': {'review_id': <PandasArray>
  [  200,   344,   346,   360,   393,   433,   508,   661,   723,   764,
   ...
   98660, 98740, 98887, 98989, 99085, 99108, 99124, 99164, 99167, 99178]
  Length: 1603, dtype: int64}}

The tables **geolocation** and **order_reviews** seems to have duplicates. Now each one shall be inspected to decide the course of action.

In [16]:
(
    dfs_dict["order_reviews"]
        .iloc[duplicated_dict["order_reviews"]["review_id"]]
        .sort_values(by="review_id")
        .head(15)
)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,<NA>,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,<NA>,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,<NA>,<NA>,2017-09-21,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,<NA>,<NA>,2017-09-21,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,<NA>,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,<NA>,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5,<NA>,<NA>,2018-03-02,2018-03-05 01:43:30
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,<NA>,<NA>,2018-03-02,2018-03-05 01:43:30
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1,<NA>,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,<NA>,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
89712,0288d42bef3dfe36930740c9588a570f,33d8795f04dd631f3480d7aaf90da3dc,3,<NA>,<NA>,2017-07-29,2017-07-31 17:11:04
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3,<NA>,<NA>,2017-07-29,2017-07-31 17:11:04
47495,02aa7f5f75e964e3c7efa59a1f515281,d8e17d5f7dacf0970d316e7c03e741e8,3,<NA>,<NA>,2017-07-27,2017-07-29 15:09:50
95860,02aa7f5f75e964e3c7efa59a1f515281,db92613c074f00e53066388d48ad7512,3,<NA>,<NA>,2017-07-27,2017-07-29 15:09:50
71165,034528cb00b6bc981847acafbdf2ae0b,e1e8e3bca903de27e9a1c72b5a5795e0,1,<NA>,<NA>,2017-05-14,2017-05-15 02:17:38

In [17]:
(
    dfs_dict["geolocation"]
    .iloc[duplicated_dict["geolocation"]["geolocation_zip_code_prefix"]]
    .sort_values(by="geolocation_zip_code_prefix")
    .head(50)
)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
864,1001,-23.549825,-46.63397,sao paulo,SP
583,1001,-23.551337,-46.634027,sao paulo,SP
596,1001,-23.550498,-46.634338,sao paulo,SP
1246,1001,-23.549292,-46.633559,sao paulo,SP
1062,1001,-23.550498,-46.634338,sao paulo,SP
235,1001,-23.550642,-46.63441,sao paulo,SP
608,1001,-23.550263,-46.634196,são paulo,SP
1384,1001,-23.549292,-46.633559,sao paulo,SP
206,1001,-23.550498,-46.634338,sao paulo,SP
1351,1001,-23.549951,-46.634027,são paulo,SP
818,1001,-23.551337,-46.634027,sao paulo,SP
429,1001,-23.550498,-46.634338,sao paulo,SP
326,1001,-23.551427,-46.634074,sao paulo,SP
1435,1001,-23.549292,-46.633559,sao paulo,SP
985,1001,-23.550498,-46.634338,sao paulo,SP
1182,1001,-23.549779,-46.633957,sao paulo,SP
771,1001,-23.550498,-46.634338,sao paulo,SP
851,1001,-23.549825,-46.63397,sao paulo,SP
1004,1001,-23.549292,-46.633559,sao paulo,SP
639,1001,-23.550498,-46.634338,sao paulo,SP
519,1001,-23.551337,-46.634027,sao paulo,SP
99,1001,-23.549292,-46.633559,sao paulo,SP
897,1001,-23.549292,-46.633559,sao paulo,SP
575,1001,-23.549779,-46.633957,são paulo,SP
912,1001,-23.550498,-46.634338,sao paulo,SP
299,1001,-23.549698,-46.633909,sao paulo,SP
678,1002,-23.548551,-46.635072,sao paulo,SP
73,1002,-23.548318,-46.635421,sao paulo,SP
514,1002,-23.548551,-46.635072,sao paulo,SP
1328,1002,-23.548551,-46.635072,sao paulo,SP
737,1002,-23.548551,-46.635072,sao paulo,SP
827,1002,-23.548878,-46.634004,sao paulo,SP
711,1002,-23.548318,-46.635421,sao paulo,SP
1251,1002,-23.544641,-46.63318,são paulo,SP
997,1002,-23.548551,-46.635072,sao paulo,SP
214,1002,-23.547417,-46.636361,sao paulo,SP
1107,1002,-23.548551,-46.635072,sao paulo,SP
516,1002,-23.548137,-46.635905,sao paulo,SP
720,1002,-23.548878,-46.634004,sao paulo,SP
184,1003,-23.549044,-46.635183,sao paulo,SP
265,1003,-23.549044,-46.635183,sao paulo,SP
799,1003,-23.549083,-46.634864,sao paulo,SP
309,1003,-23.54896,-46.636172,sao paulo,SP
500,1003,-23.548976,-46.635322,sao paulo,SP
873,1003,-23.549044,-46.635183,sao paulo,SP
853,1003,-23.54894,-46.636788,sao paulo,SP
90,1003,-23.549032,-46.635313,sao paulo,SP
478,1003,-23.549083,-46.634864,são paulo,SP
179,1003,-23.548901,-46.637157,sao paulo,SP
524,1003,-23.54896,-46.636172,sao paulo,SP

---
# 3. Data Cleaning and Transformation

## Manage missing data
In **orders** table is possible to have orders without comments, so values can stay null. For **products** with no category they are assigned "Unknown", the other fields values are set to -1 as a way to identify them in consults.

In [18]:
def manage_nans(dfs_dict) -> None:
    dfs_dict[products_df.name] = dfs_dict[products_df.name].fillna({
        "product_category_name": "Unknown",
        "product_name_lenght": -1,
        "product_description_lenght": -1,
        "product_photos_qty": -1,
        "product_weight_g": -1,
        "product_length_cm": -1,
        "product_height_cm": -1,
        "product_width_cm": -1
    })

In [19]:
manage_nans(dfs_dict)
check_nans(dfs_dict)

Nans in: order_reviews | Column: review_comment_title. | Quantity: 87656
Nans in: order_reviews | Column: review_comment_message. | Quantity: 58247

## Manage Duplicates

For these cases, duplicates seems to have the same information, so the first found value is kept and the rest deleted.

In [20]:
dfs_dict["order_reviews"] = dfs_dict["order_reviews"].drop_duplicates(subset=["review_id"], keep="first")
dfs_dict["geolocation"] = dfs_dict["geolocation"].drop_duplicates(subset=["geolocation_zip_code_prefix"], keep="first")

In [21]:
duplicated_dict = find_duplicates(dfs_dict, unique_fields_dict)
duplicated_dict

{}

# Export to database

from sqlalchemy import create_engine

engine = create_engine("sqlite:///../Data/Brazilian_E-Commerc_Database.db")

for name, df in dfs_dict.items():
    df.to_sql(
        name=name,
        con=engine,
        if_exists="append",
        index=False
    )