# Import libraries

In [1]:
import pandas as pd

from sqlalchemy import (
    create_engine, MetaData, Table, Column,
    String, Integer, ForeignKey
)

---
# 1. Data Ingestion

In [2]:
# Declare csv data types
dtypes_dict = {
    "customer_id": "string",
    "customer_unique_id": "string",
    "customer_zip_code_prefix": "Int64",
    "customer_city": "string",
    "customer_state": "string"
}

customers_df = pd.read_csv("../Data/csvs/olist_customers_dataset.csv", dtype=dtypes_dict)
customers_df.name = "customers"
# customers_df.dtypes

In [3]:
# Declare csv data types
dtypes_dict = {
    "geolocation_zip_code_prefix": "Int64",
    "geolocation_lat": "Float64",
    "geolocation_lng": "Float64",
    "geolocation_city": "string",
    "geolocation_state": "string"
}

geolocation_df = pd.read_csv("../Data/csvs/olist_geolocation_dataset.csv", dtype=dtypes_dict)
geolocation_df.name = "geolocation"
# geolocation_df.dtypes

In [4]:
# Declare csv data types
dtypes_dict = {
    "order_id": "string",
    "order_item_id": "Int64",
    "product_id": "string",
    "seller_id": "string",
    "shipping_limit_date": "string",
    "price": "Float64",
    "freight_value": "Float64"
}

# It is not expected to have wrong dates format, so the conversion can be at reading
dates_columns = [
        "shipping_limit_date"
    ]

order_items_df = pd.read_csv(
    "../Data/csvs/olist_order_items_dataset.csv", 
    dtype=dtypes_dict,
    parse_dates=dates_columns
)
order_items_df.name = "order_items"
# order_items_df.dtypes

In [5]:
# Declare csv data types
dtypes_dict = {
    "order_id": "string",
    "payment_sequential": "Int64",
    "payment_type": "string",
    "payment_installments": "Int64",
    "payment_value": "Float64"
}

order_payments_df = pd.read_csv("../Data/csvs/olist_order_payments_dataset.csv", dtype=dtypes_dict)
order_payments_df.name = "order_payments"
# order_payments_df.dtypes

In [6]:
# Declare csv data types
dtypes_dict = {
    "review_id": "string",
    "order_id": "string",
    "review_score": "Int64",
    "review_comment_title": "string",
    "review_comment_message": "string",
    "review_creation_date": "string",
    "review_answer_timestamp": "string"
}

# It is not expected to have wrong dates format, so the conversion can be at reading
dates_columns = [
        "review_creation_date", 
        "review_answer_timestamp"
    ]

order_reviews_df = pd.read_csv(
    "../Data/csvs/olist_order_reviews_dataset.csv", 
    dtype=dtypes_dict,
    parse_dates=dates_columns
)
order_reviews_df.name = "order_reviews"
# order_reviews_df.dtypes

In [7]:
# Declare csv data types
dtypes_dict = {
    "order_id": "string",
    "customer_id": "string",
    "order_status": "string",
    "order_purchase_timestamp": "string",
    "order_approved_at": "string",
    "order_delivered_carrier_date": "string",
    "order_delivered_customer_date": "string",
    "order_estimated_delivery_date": "string"
}

# It is not expected to have wrong dates format, so the conversion can be at reading
dates_columns = [
        "order_purchase_timestamp",
        "order_approved_at", 
        "order_delivered_carrier_date", 
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]

orders_df = pd.read_csv(
    "../Data/csvs/olist_orders_dataset.csv", 
    dtype=dtypes_dict,
    parse_dates=dates_columns
)
orders_df.name = "orders"
# orders_df.dtypes

In [8]:
# Declare csv data types
dtypes_dict = {
    "product_id": "string",
    "product_category_name": "string",
    "product_name_lenght": "Int64",
    "product_description_lenght": "Int64",
    "product_photos_qty": "Int64",
    "product_weight_g": "Int64",
    "product_length_cm": "Int64",
    "product_height_cm": "Int64",
    "product_width_cm": "Int64",
}

products_df = pd.read_csv("../Data/csvs/olist_products_dataset.csv", dtype=dtypes_dict)
products_df.name = "products"
# products_df.dtypes

In [9]:
# Declare csv data types
dtypes_dict = {
    "seller_id": "string",
    "seller_zip_code_prefix": "Int64",
    "seller_city": "string",
    "seller_state": "string",
}

sellers_df = pd.read_csv("../Data/csvs/olist_sellers_dataset.csv", dtype=dtypes_dict)
sellers_df.name = "sellers"
# sellers_df.dtypes

In [10]:
# Declare csv data types
dtypes_dict = {
    "product_category_name": "string",
    "product_category_name_english": "string"
}

product_category_name_translation_df = pd.read_csv("../Data/csvs/product_category_name_translation.csv", dtype=dtypes_dict)
product_category_name_translation_df.name = "product_category_name_translation"
# product_category_name_translation_df.dtypes

In [11]:
# Create dataframes dictionary
dfs_dict = {
    customers_df.name: customers_df,
    geolocation_df.name: geolocation_df,
    order_items_df.name: order_items_df,
    order_payments_df.name: order_payments_df,
    order_reviews_df.name: order_reviews_df,
    orders_df.name: orders_df,
    products_df.name: products_df,
    sellers_df.name: sellers_df,
    product_category_name_translation_df.name: product_category_name_translation_df
}

---
# 2. Data Quality Analysis

## 2.1. Missing data

In [12]:
# Get what columns from which dataframes contains nulls
def check_nans(dfs_dict) -> None:
    for df in dfs_dict.values():
        nans_df = df.isna().sum()
        nans_df = nans_df[nans_df > 0]

        for column, quantity in nans_df.items():
            print(f"Nans in: {df.name} | Column: {column}. | Quantity: {quantity}")

In [13]:
check_nans(dfs_dict)

Nans in: order_reviews | Column: review_comment_title. | Quantity: 87656
Nans in: order_reviews | Column: review_comment_message. | Quantity: 58247
Nans in: products | Column: product_category_name. | Quantity: 610
Nans in: products | Column: product_name_lenght. | Quantity: 610
Nans in: products | Column: product_description_lenght. | Quantity: 610
Nans in: products | Column: product_photos_qty. | Quantity: 610
Nans in: products | Column: product_weight_g. | Quantity: 2
Nans in: products | Column: product_length_cm. | Quantity: 2
Nans in: products | Column: product_height_cm. | Quantity: 2
Nans in: products | Column: product_width_cm. | Quantity: 2

## 2.2. Duplicates

In [14]:
unique_fields_dict = {
    customers_df.name: ["customer_id"],
    geolocation_df.name: ["geolocation_zip_code_prefix"],
    order_reviews_df.name: ["review_id"],
    orders_df.name: ["order_id"],
    products_df.name: ["product_id"],
    sellers_df.name: ["seller_id"]
}

def find_duplicates(dfs_dict, unique_fields_dict) -> None:
    duplicated_dict = {}
    for name, columns in unique_fields_dict.items():
        for column in columns:
            temp_s = dfs_dict[name][column].duplicated(keep=False)
            temp_ar = temp_s[temp_s].index.array
            if (temp_ar.size > 0):
                duplicated_dict[name] = {column: temp_ar}

    return duplicated_dict

In [15]:
duplicated_dict = find_duplicates(dfs_dict, unique_fields_dict)
duplicated_dict

{'geolocation': {'geolocation_zip_code_prefix': <PandasArray>
  [      0,       1,       2,       3,       4,       5,       6,       7,
         8,       9,
   ...
   1000153, 1000154, 1000155, 1000156, 1000157, 1000158, 1000159, 1000160,
   1000161, 1000162]
  Length: 999120, dtype: int64},
 'order_reviews': {'review_id': <PandasArray>
  [  200,   344,   346,   360,   393,   433,   508,   661,   723,   764,
   ...
   98660, 98740, 98887, 98989, 99085, 99108, 99124, 99164, 99167, 99178]
  Length: 1603, dtype: int64}}

The tables **geolocation** and **order_reviews** seems to have duplicates. Now each one shall be inspected to decide the course of action.

In [16]:
(
    dfs_dict["order_reviews"]
        .iloc[duplicated_dict["order_reviews"]["review_id"]]
        .sort_values(by="review_id")
        .head(15)
)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,<NA>,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,<NA>,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,<NA>,<NA>,2017-09-21,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,<NA>,<NA>,2017-09-21,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,<NA>,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,<NA>,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5,<NA>,<NA>,2018-03-02,2018-03-05 01:43:30
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,<NA>,<NA>,2018-03-02,2018-03-05 01:43:30
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1,<NA>,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,<NA>,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
89712,0288d42bef3dfe36930740c9588a570f,33d8795f04dd631f3480d7aaf90da3dc,3,<NA>,<NA>,2017-07-29,2017-07-31 17:11:04
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3,<NA>,<NA>,2017-07-29,2017-07-31 17:11:04
47495,02aa7f5f75e964e3c7efa59a1f515281,d8e17d5f7dacf0970d316e7c03e741e8,3,<NA>,<NA>,2017-07-27,2017-07-29 15:09:50
95860,02aa7f5f75e964e3c7efa59a1f515281,db92613c074f00e53066388d48ad7512,3,<NA>,<NA>,2017-07-27,2017-07-29 15:09:50
71165,034528cb00b6bc981847acafbdf2ae0b,e1e8e3bca903de27e9a1c72b5a5795e0,1,<NA>,<NA>,2017-05-14,2017-05-15 02:17:38

In [17]:
(
    dfs_dict["geolocation"]
    .iloc[duplicated_dict["geolocation"]["geolocation_zip_code_prefix"]]
    .sort_values(by="geolocation_zip_code_prefix")
    .head(50)
)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
864,1001,-23.549825,-46.63397,sao paulo,SP
583,1001,-23.551337,-46.634027,sao paulo,SP
596,1001,-23.550498,-46.634338,sao paulo,SP
1246,1001,-23.549292,-46.633559,sao paulo,SP
1062,1001,-23.550498,-46.634338,sao paulo,SP
235,1001,-23.550642,-46.63441,sao paulo,SP
608,1001,-23.550263,-46.634196,são paulo,SP
1384,1001,-23.549292,-46.633559,sao paulo,SP
206,1001,-23.550498,-46.634338,sao paulo,SP
1351,1001,-23.549951,-46.634027,são paulo,SP
818,1001,-23.551337,-46.634027,sao paulo,SP
429,1001,-23.550498,-46.634338,sao paulo,SP
326,1001,-23.551427,-46.634074,sao paulo,SP
1435,1001,-23.549292,-46.633559,sao paulo,SP
985,1001,-23.550498,-46.634338,sao paulo,SP
1182,1001,-23.549779,-46.633957,sao paulo,SP
771,1001,-23.550498,-46.634338,sao paulo,SP
851,1001,-23.549825,-46.63397,sao paulo,SP
1004,1001,-23.549292,-46.633559,sao paulo,SP
639,1001,-23.550498,-46.634338,sao paulo,SP
519,1001,-23.551337,-46.634027,sao paulo,SP
99,1001,-23.549292,-46.633559,sao paulo,SP
897,1001,-23.549292,-46.633559,sao paulo,SP
575,1001,-23.549779,-46.633957,são paulo,SP
912,1001,-23.550498,-46.634338,sao paulo,SP
299,1001,-23.549698,-46.633909,sao paulo,SP
678,1002,-23.548551,-46.635072,sao paulo,SP
73,1002,-23.548318,-46.635421,sao paulo,SP
514,1002,-23.548551,-46.635072,sao paulo,SP
1328,1002,-23.548551,-46.635072,sao paulo,SP
737,1002,-23.548551,-46.635072,sao paulo,SP
827,1002,-23.548878,-46.634004,sao paulo,SP
711,1002,-23.548318,-46.635421,sao paulo,SP
1251,1002,-23.544641,-46.63318,são paulo,SP
997,1002,-23.548551,-46.635072,sao paulo,SP
214,1002,-23.547417,-46.636361,sao paulo,SP
1107,1002,-23.548551,-46.635072,sao paulo,SP
516,1002,-23.548137,-46.635905,sao paulo,SP
720,1002,-23.548878,-46.634004,sao paulo,SP
184,1003,-23.549044,-46.635183,sao paulo,SP
265,1003,-23.549044,-46.635183,sao paulo,SP
799,1003,-23.549083,-46.634864,sao paulo,SP
309,1003,-23.54896,-46.636172,sao paulo,SP
500,1003,-23.548976,-46.635322,sao paulo,SP
873,1003,-23.549044,-46.635183,sao paulo,SP
853,1003,-23.54894,-46.636788,sao paulo,SP
90,1003,-23.549032,-46.635313,sao paulo,SP
478,1003,-23.549083,-46.634864,são paulo,SP
179,1003,-23.548901,-46.637157,sao paulo,SP
524,1003,-23.54896,-46.636172,sao paulo,SP

---
# 3. Data Cleaning and Transformation

## 3.1. Manage missing data
In **orders** table is possible to have orders without comments, so values can stay null. For **products** with no category they are assigned "Unknown", the other fields values are set to -1 as a way to identify them in consults.

In [18]:
def manage_nans(dfs_dict) -> None:
    dfs_dict[products_df.name] = dfs_dict[products_df.name].fillna({
        "product_category_name": "Unknown",
        "product_name_lenght": -1,
        "product_description_lenght": -1,
        "product_photos_qty": -1,
        "product_weight_g": -1,
        "product_length_cm": -1,
        "product_height_cm": -1,
        "product_width_cm": -1
    })

In [19]:
manage_nans(dfs_dict)
check_nans(dfs_dict)

Nans in: order_reviews | Column: review_comment_title. | Quantity: 87656
Nans in: order_reviews | Column: review_comment_message. | Quantity: 58247

## 3.2. Manage Duplicates
For these cases, duplicates seems to have the same information, so the first found value is kept and the rest deleted.

In [20]:
dfs_dict["order_reviews"] = dfs_dict["order_reviews"].drop_duplicates(subset=["review_id"], keep="first")
dfs_dict["geolocation"] = dfs_dict["geolocation"].drop_duplicates(subset=["geolocation_zip_code_prefix"], keep="first")

In [21]:
duplicated_dict = find_duplicates(dfs_dict, unique_fields_dict)
duplicated_dict

{}

---
# 4. Feature engineering

## 4.1. Customers

In [22]:
# Main dataframe where to read from in the next steps
main_customers_fe_df = (
    dfs_dict["customers"]
    .merge(dfs_dict["orders"], how="left", on="customer_id")
    .merge(dfs_dict["order_payments"], how="left", on="order_id")
    .merge(dfs_dict["order_items"], how="left", on="order_id")
    .merge(dfs_dict["order_reviews"], how="left", on="order_id")
)
main_customers_fe_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,seller_id,shipping_limit_date,price,freight_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88,88b8b52d46df026a9d1ad2136a59b30b,4,<NA>,<NA>,2017-05-26,2017-05-30 22:34:40
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.0,46.48,02fc48a9efa3e3d0f1a8ea26507eeec3,5,<NA>,<NA>,2018-01-30,2018-02-10 22:43:29
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79,5ad6695d76ee186dc473c42706984d87,5,<NA>,<NA>,2018-06-15,2018-06-15 12:10:59
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36,059a801bb31f6aab2266e672cab87bc5,5,<NA>,<NA>,2018-03-29,2018-04-02 18:36:47
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.0,22.25,8490879d58d6c5d7773f2739a03f089a,5,a melhor nota,O baratheon è esxelente Amo adoro o baratheon,2018-08-10,2018-08-17 01:59:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118758,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,...,527801b552d0077ffd170872eb49683b,2018-04-12 16:08:45,74.9,13.88,36e2cdbaa9f639b57c53b37ac798fee8,4,Recomendo,<NA>,2018-04-14,2018-04-28 11:15:04
118759,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,...,3fd1e727ba94cfe122d165e176ce7967,2018-04-10 08:35:12,114.9,14.16,b273b431c3aedb4eed18643309652940,5,<NA>,<NA>,2018-04-12,2018-04-16 10:36:05
118760,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,...,d9e7e7778b32987280a6f2cb9a39c57d,2018-04-12 20:30:03,37.0,19.04,fa4f16891e6b2edd1354668d07f5648b,1,Chateada,Esperava qualidade no atendimento e estou tend...,2018-05-04,2018-05-08 01:41:07
118761,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,...,4869f7a5dfa277a7dca6462dcf3b52b2,2017-11-09 21:15:51,689.0,22.07,0bcdc9e450ea500811a8d39ee993cd47,5,<NA>,<NA>,2017-11-17,2017-11-19 23:34:18
118762,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,...,3c7c4a49ec3c6550809089c6a2ca9370,2017-12-26 18:50:39,13.99,7.78,d95d701d062d2bb88041768a63aa750d,5,<NA>,"Produto chegou bem antes do prazo , gostei mui...",2017-12-27,2017-12-27 23:21:06

### 4.1.1. Customer Lifetime Value (LTV) 
It is the cumulative net value attributed to a customer from their first purchase to their last, including all transactions during that period.

In [23]:
# Read orders money columns
temp_customers_fe_df = (
    main_customers_fe_df
    [["order_id", "order_item_id", "price", "freight_value", "payment_value"]]
    .copy()
)
# Create new columns and data
temp_customers_fe_df["order_value"] = (temp_customers_fe_df["price"] + temp_customers_fe_df["freight_value"]) * temp_customers_fe_df["order_item_id"]
temp_customers_fe_df["profit_based_LTV"] = (temp_customers_fe_df["payment_value"] - temp_customers_fe_df["order_value"])
temp_customers_fe_df = (
    temp_customers_fe_df[["order_id", "order_value", "payment_value", "profit_based_LTV"]]
    .groupby("order_id", as_index=False).sum()
    .sort_values(by="profit_based_LTV", ascending=False)
)
# Link the new data to its costumers
customers_fe_df = (
    temp_customers_fe_df[["order_id", "profit_based_LTV"]]
    .copy()
)
customers_fe_df = (
    customers_fe_df
    .merge(main_customers_fe_df[["order_id", "customer_unique_id"]], how="left", on="order_id")
    [["customer_unique_id", "profit_based_LTV"]]
    .groupby("customer_unique_id", as_index=False).mean()
    .sort_values(by="customer_unique_id", ascending=False)
)
customers_fe_df

                     customer_unique_id  profit_based_LTV
96095  ffffd2657e2aad2907e67c3e9daecbeb               0.0
96094  ffff5962728ec6157033ef9805bacc48               0.0
96093  ffff371b4d645b6ecea244b27531430a              -0.0
96092  fffea47cd6d3cc0a88bd621562a9d061               0.0
96091  fffcf5a5ff07b0908bd4e2dbc735a684           1148.28
...                                 ...               ...
4      0004aac84e0df4da2b147fca70cf8255               0.0
3      0000f6ccb0745a6a4b88665a16c9f078               0.0
2      0000f46a3911fa3c0805444483337064               0.0
1      0000b849f77a49e4a4ce2b2a4ca5be3f               0.0
0      0000366f3b9a7992bf8c76cfdf3221e2               0.0

[96096 rows x 2 columns]

### 4.1.2. Average order and payment value

In [24]:
# Extract customers order and payment values 
temp_customers_fe_df = (
    temp_customers_fe_df
    .merge(main_customers_fe_df[["order_id", "customer_unique_id"]], how="left", on="order_id")
    [["customer_unique_id", "order_value", "payment_value"]]
    .groupby("customer_unique_id", as_index=False).sum()
    .sort_values(by="customer_unique_id", ascending=False)
)
customers_fe_df = (
    customers_fe_df
    .merge(temp_customers_fe_df, how="left", on="customer_unique_id")
)
customers_fe_df

,customer_unique_id,profit_based_LTV,order_value,payment_value
0,ffffd2657e2aad2907e67c3e9daecbeb,0.0,71.56,71.56
1,ffff5962728ec6157033ef9805bacc48,0.0,133.69,133.69
2,ffff371b4d645b6ecea244b27531430a,-0.0,112.46,112.46
3,fffea47cd6d3cc0a88bd621562a9d061,0.0,84.58,84.58
4,fffcf5a5ff07b0908bd4e2dbc735a684,1148.28,5973.12,8269.68
...,...,...,...,...
96091,0004aac84e0df4da2b147fca70cf8255,0.0,196.89,196.89
96092,0000f6ccb0745a6a4b88665a16c9f078,0.0,43.62,43.62
96093,0000f46a3911fa3c0805444483337064,0.0,86.22,86.22
96094,0000b849f77a49e4a4ce2b2a4ca5be3f,0.0,27.19,27.19
96095,0000366f3b9a7992bf8c76cfdf3221e2,0.0,141.9,141.9

### 4.1.3. Days since last purchase

In [25]:
# Get last purchase per customer
temp_df = (
    main_customers_fe_df[["customer_unique_id", "order_purchase_timestamp"]]
    .groupby("customer_unique_id", as_index=False).max()
)
# Get last purchase
last_purchase_datetime = temp_df["order_purchase_timestamp"].max()
# Calculate costumers days
temp_df["days_since_purchase"] = (last_purchase_datetime - temp_df["order_purchase_timestamp"]).dt.days
temp_df = (
    temp_df[["customer_unique_id", "days_since_purchase"]]
    .groupby("customer_unique_id", as_index=False).min()
    .sort_values(by="customer_unique_id", ascending=False)
)
temp_df

                     customer_unique_id  days_since_purchase
96095  ffffd2657e2aad2907e67c3e9daecbeb                  532
96094  ffff5962728ec6157033ef9805bacc48                  168
96093  ffff371b4d645b6ecea244b27531430a                  617
96092  fffea47cd6d3cc0a88bd621562a9d061                  310
96091  fffcf5a5ff07b0908bd4e2dbc735a684                  495
...                                 ...                  ...
4      0004aac84e0df4da2b147fca70cf8255                  336
3      0000f6ccb0745a6a4b88665a16c9f078                  369
2      0000f46a3911fa3c0805444483337064                  585
1      0000b849f77a49e4a4ce2b2a4ca5be3f                  163
0      0000366f3b9a7992bf8c76cfdf3221e2                  160

[96096 rows x 2 columns]

In [26]:
customers_fe_df = (
    customers_fe_df
    .merge(temp_df, how="left", on="customer_unique_id")
    .sort_values(by="customer_unique_id", ascending=False)
)
customers_fe_df

,customer_unique_id,profit_based_LTV,order_value,payment_value,days_since_purchase
0,ffffd2657e2aad2907e67c3e9daecbeb,0.0,71.56,71.56,532
1,ffff5962728ec6157033ef9805bacc48,0.0,133.69,133.69,168
2,ffff371b4d645b6ecea244b27531430a,-0.0,112.46,112.46,617
3,fffea47cd6d3cc0a88bd621562a9d061,0.0,84.58,84.58,310
4,fffcf5a5ff07b0908bd4e2dbc735a684,1148.28,5973.12,8269.68,495
...,...,...,...,...,...
96091,0004aac84e0df4da2b147fca70cf8255,0.0,196.89,196.89,336
96092,0000f6ccb0745a6a4b88665a16c9f078,0.0,43.62,43.62,369
96093,0000f46a3911fa3c0805444483337064,0.0,86.22,86.22,585
96094,0000b849f77a49e4a4ce2b2a4ca5be3f,0.0,27.19,27.19,163
96095,0000366f3b9a7992bf8c76cfdf3221e2,0.0,141.9,141.9,160

### 4.1.4. Average review score

# Export to database

engine = create_engine("sqlite:///../Data/Brazilian_E-Commerc_Database.db")

for name, df in dfs_dict.items():
    df.to_sql(
        name=name,
        con=engine,
        if_exists="append",
        index=False
    )